# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alan Haskins
title: Principal Software Engineer
email: alan_haskins@hotmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  alanhaskins
linkedin_username: alan-haskins-52a45116a

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a principal software engineer with 10 years' experience within a large IT organization. I've quickly progressed from internship through the grades to tech leading applications with 100,000 daily users.

  I've experience across a variety of projects and exposure to range of tools and techniques. In the last few years I've worked on building some of the first cloud native architectures within LIT as well as building and designing a number of event driven solutions. Most recently I've been tech leading a junior team through challenging work build a new home quoting application as well as designing and innovating on product agnostic core services that will enable teams to quickly spin up and roll out rating programs going forward.

  I particularly enjoy experimentation and innovation. POCing new concepts. Cloud native and serverless architectures. Working closely with other developers to design complex systems and concepts.

  Skilled in performance, stability and security analysis.

content:
  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Liberty IT, Belfast
        sub_title: Principal Software Engineer
        caption: May 2019 - Present
        description: | # this will include new lines to allow paragraphs
          - Rating programing and UI build out
            - React, AWS, NodeJS, Typescript, DocumentDB, SNS, SQS
          - Significant throughput expectations
          - Event Driven Architecture
            - Architecture design and reviews
            - POCing and thorough analysis of products. EventBridge vs Kafka vs AWS MSK Kafka.
            - Experiementation and POC of EventBridge, Manage Streaming for Kafka (AWS MSK), Elasticache
            - Kafka and container applications and AWS integration
          - Reuse
          - Automation (CDK)
            - Innovation & experimentation
            - Fargate solution
            - Lambda Power Tuner
            - Storybook
            - Artillery test suites
            - Snyk security testing, reuse idea from other areas, first added to Sales space
            - Kafka Connect POC
          - Mentoring / Team structure
            - New starts
            - Code reviews
            - Lightning Talks
            - Pair programming
            - Ramping new devs up in unfamiliar domains
            - Coaching (specifically autism)
            - Task delegation, reviews and feedback
          - Organized and heavily contributed to Well Architected Reviews for AWS workloads
          - Working with PO to define stories, backlogs. Leading agile ceremonies.
          - Agile methodologies. Agile and pushed for switch to Kanban to facilitate the work type
          - Demos, technical discussions with high up technical people. Cross team impacts.
          - Total Cost of Ownership considerations

          **Technologies used**: CFT, CDK, Serverless, Lambda, SNS, SQS, API Gateway, DynamoDB, React, Typescript, NodeJS, Git. Experimentation with EventBridge, AWS MSK and Kafka.

      - layout: left
        title: Liberty IT, Belfast
        sub_title: Senior Software Engineer
        caption: April 2014 – May 2019
        description: | # this will include new lines to allow paragraphs
          - Technology used
          - DOJO, Java, Process  Server, BPM, mobile app testing
          - AWS services used
          - Modernization
          - ADIL
          - Virus scanner
          - Threat modelling and taking through security review
          - SELF STUDY
          - AWS, React
          - PSS and innovation sprint
          - Performance optimzation
          - TECH LEAD
          - Projects
          - PCI
          - Life Policy
          - Monthly Release
          - Dojo Upgrade
          - OPC rollout
          - DUBLIN / US Teams ramp up and mentoring to be self sufficient
          - Presentation, architecture walk throughs, pair programming
          - 2 weeks in US
          - A/B Testing
          - Exploratory Testing
          - Performance Testing
          - BDD
          - Code reviews
          - Tech talks
          - Inner sourcing
          - TCO analysis

          **Technologies used**: CFT, Serverless, Lambda, API Gateway, DynamoDB, React, NodeJS, DOJO, Java, Process Server, BPM. Experimentation with AWS Rekognition and TextTract.

      - layout: left
        title: Liberty IT, Belfast
        sub_title: Associate Software Engineer / Software Engineer
        caption: June 2011 – April 2014
        description: | # this will include new lines to allow paragraphs
            - Technology used
            - Unit, integration, exploratory testing
            - Various projects
            - Make a payment
            - Home page redesign (distributed teams)
            - Working closely with business teams
            - Initially mostly waterfall projects
            - OPC
            - Deadlines, £20m budget
            - Data analytics. Analytics Framework. Worked wi
            - Front End guidance teams
            - Science fairs

            **Technologies used**: DOJO, Java, Process Server, BPM, Omniture

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Distribution Capabilities Platform


        description: | # this will include new lines to allow paragraphs
          Project Description and technology used?

      - layout: top-middle
        title: Oasis 2 Rating Program


        description: | # this will include new lines to allow paragraphs
          Project Description and technology used?

      - layout: top-middle
        title: Online Policy Change Modernization


        description: | # this will include new lines to allow paragraphs
          Project Description and technology used?

      - layout: top-middle
        title: ADIL


        description: | # this will include new lines to allow paragraphs
          Project Description and technology used?

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Queen's University Belfast
        caption: 2006 - 2011
        sub_title: BSc Computing and Information Technology
        description: | # this will include new lines to allow paragraphs
          I recieved 1st class honours from my CIT course and received an award for best performing student on this course.

  - title: Interests
    layout: text
    content: | # this will include new lines to allow paragraphs
      Aside from technology, my other interests include:
      - Barbecueing
      - Running
      - Reading

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
