# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alan Haskins
title: Principal Software Engineer
email: alan_haskins@hotmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  alanhaskins
linkedin_username: alan-haskins-52a45116a

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a principal software engineer with 10 years' experience within a large IT organization. I've quickly progressed from internship through the grades to tech leading applications with 100,000 daily users (TODO: check this).

  I've experience across a variety of projects and exposure to range of tools and techniques. In the last few years I've worked on designing and implementing cloud native services and event driven solutions. Most recently I've been tech leading a junior team through challenging work build a new home quoting application as well as designing and innovating on product agnostic services to enable teams to quickly spin up and roll out future rating programs.

  I particularly enjoy experimentation, innovating and testing proof of concepts on cloud native and serverless architectures, as well working closely with other developers to design complex systems and concepts.

  My projects have given me opportunities to take ownership of the performance, stability and security of my applications and Ive developed a strong focus on these aspects in my deliverables.

content:
  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Liberty IT, Belfast
        sub_title: Principal Software Engineer
        caption: May 2019 - Present
        description: | # this will include new lines to allow paragraphs
          **Roles and responsibilities included**:

          - Providing technical leadership on a team creating a UI and services as part of a new home quoting system, as well as a core capabilities platform and event driven architecture
          - POCing a number of technology options and designing alternative solutions to complex problems, including total cost of ownership of solutions
          - Working closely across teams and with senior technical leaders to gather system requirements, demo and review solutions
          - Innovating and reusing solutions to improve performance and speed to market for our applications.
            - Including contributing some of the first components to our internal CDK repo, introducing storybook component library, artillery performance testing, lambda performance tuning, reusable proxy solution and Kafka to lambda enablement.
          - Working with product owner and team to define and prioritize stories in a technically complex domain
          - Mentoring an inexperienced team via code reviews, pair programming, architectural overviews and lightning talks
          - Organizing and contributing to Well Architected Reviews for AWS workloads

      - layout: left
        title: Liberty IT, Belfast
        sub_title: Senior Software Engineer
        caption: April 2014 – May 2019
        description: | # this will include new lines to allow paragraphs
          **Roles and responsibilities included**:

          - Tech lead on a number of agile projects and worked closely with team, product owners and business partners to define workloads
          - Responsible for delivering secure, stable and performant applications, working on project design through to production delivery and maintenance
          - Worked on some of the first AWS cloud native architectures in Liberty Mutual, primarily learning through self directed study
          - Developed applications with a Performance, Stability and Security (PSS) focussed mentality
          - Creation of a PSS application and led cross team initiative to engage teams to improve PSS aspects of their applications
          - Took projects though security review processes and implemented an antivirus scanner to protect our resources against unsafe files
          - Mentoring and transitioning of workloads to  remote teams, including spending 2 weeks in US to provide support to new teams
          - Built experience in a number of techniques including pair programming, exploratory testing, threat modelling, A/B testing and BDD

      - layout: left
        title: Liberty IT, Belfast
        sub_title: Associate Software Engineer / Software Engineer
        caption: June 2011 – April 2014
        description: | # this will include new lines to allow paragraphs
            **Roles and responsibilities included**:

            - Proving myself as a trusted and capable team member who could work on a variety of tasks autonomously
            - Quickly understanding and undertaking work in unfamiliar domains and technologies
            - Working closely with business partners and remote team members and delivering on projects, primarily via waterfall methodology
            - Validating code deliveries via unit, integration and exploratory testing
            - Working with technical leaders and other project teams to gather requirements and implement an analytics framework in a high pressure environment
            - Participated in guidance teams to ensure code quality and consistency across teams
            - Represented LIT at external events such as graduate science fairs

            **Technologies used**: DOJO, Java, Process Server, BPM, Omniture

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Distribution Capabilities Platform

        description: | # this will include new lines to allow paragraphs
          Creating a number of product agnostic and event driven services to enable faster development of future quoting systems.

          **Technologies used**: CFT, CDK, Serverless, Lambda, SNS, SQS, API Gateway, DynamoDB, DocumentDB, React, Typescript, NodeJS, GraphQL, REST, Git, Bamboo, Splunk, Datadog. Experimentation with EventBridge, AWS MSK and Kafka.

      - layout: left
        title: Oasis 2 Home Quoting

        description: | # this will include new lines to allow paragraphs
          A UI and services to support quoting, rating and binding of home policies through liberymutual.com

          **Technologies used**: CFT, CDK, Serverless, Lambda, SNS, SQS, API Gateway, DynamoDB, React, Typescript, NodeJS, GraphQL, REST, Git, Bamboo, Splunk, Datadog.

      - layout: left
        title: Serverless Policy Endorsements (OPC)

        description: | # this will include new lines to allow paragraphs
          Using event driven architectures to automate policy endorsement opportunities for customers.

          **Technologies used**: CFT, Lambda, Step Functions, Fargate, API Gateway, DynamoDB, S3, React, NodeJS, REST, Git, Jenkins.

      - layout: left
        title: Auto Damage Inspection at Liberty

        description: | # this will include new lines to allow paragraphs
          Cloud native mobile and agent applications to improve policy purchase time by enabling customers to upload vehicle images for approval

          **Technologies used**: Serverless, Lambda, API Gateway, DynamoDB, S3, React, Yaml, NodeJS, REST, Git, Jenkins. Experimentation with Rekognition and TextTract.

      - layout: left
        title: Previous Projects

        description: | # this will include new lines to allow paragraphs
          I've worked on a range of projects in the last 10 years, primarily within the digital Service organization of Liberty Mutual, providing functionality for millions of users.

            **Technologies used**: React, DOJO, Java, IBM Process Server, BPEL, Siteminder, MongoDB, Drools.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Queen's University Belfast
        caption: 2006 - 2011
        sub_title: BSc Computing and Information Technology
        description: | # this will include new lines to allow paragraphs
          I received 1st class honours from my CIT course and received an award for best performing student on this course.

  - title: Interests
    layout: text
    content: | # this will include new lines to allow paragraphs
      Aside from technology, my other interests include:
      - Barbecueing
      - Running
      - Reading

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
