# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alan Haskins
title: Principal Software Engineer
email: alan_haskins@hotmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  alanhaskins
linkedin_username: alan-haskins-52a45116a

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a software engineer with 12.5 years experience across a couple of large IT organizations. 
  
  At LibertyIT, I quickly progressed from internship through the grades to tech leading high traffic applications. For a new challenge, I moved to Globalization Partners to re-imagine a complex monolithic Java/RDS system into an event driven, serverless ecosystem.

  I am an experienced AWS and Serverless engineer with knowledge of building scalable, business critical services.
  
  I have had exposure to many projects and a range of tools and techniques. One of my strengths is my ability to quickly learn and implement effectivelty with unfamiliar technologies.

  I particularly enjoy experimentation; innovating and testing proof of concepts on cloud native and serverless architectures, as well working closely with other developers to design complex systems and concepts.

  My projects have given me opportunities to take ownership of the performance, stability and security of my applications and I have developed a strong focus on these aspects in my deliverables.

  In previous roles I have spent time leading teams of junior engineers through complex workloads. More recently I have been closely engaging with senior techincal leaders and influencing the technology direction at GP.

content:
  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Globalization Partners, Belfast
        sub_title: Senior Software Engineer
        caption: August 2021 - Present
        description: | # this will include new lines to allow paragraphs
          **Roles and responsibilities include**:

          - Introduced some of the first Serverless workloads to GP and instrumental in the shift from monolith to team owned microservices
          - Worked to move infrastucture towards team ownership rather than overloaded DevOps teams
          - Innovating and proving out a number of technologies for the first time in GP as well as feeding back to technical leaders
          -- Including Step Functions, EventBridge, EventBridge Pipes
          - Became a contact for developers for all Serverless queries and mentored team members on AWS technology to share learnings
          - Running well architected reviews, threat models, performance testing, production monitoring
          - Tech lead on a number of API and event driven serverless projects
          
      - layout: left
        title: Liberty IT, Belfast
        sub_title: Principal Software Engineer
        caption: May 2019 - August 2021
        description: | # this will include new lines to allow paragraphs
          **Roles and responsibilities include**:

          - Providing technical leadership on a team creating a UI and services as part of a new home quoting system, as well as a core capabilities platform and event driven architecture
          - POCing a number of technology options and designing alternative solutions to complex problems, including total cost of ownership of solutions
          - Working closely across teams and with senior technical leaders to gather system requirements, demo and review solutions
          - Innovating and reusing solutions to improve performance and speed to market for our applications. This includes contributing some of the first components to our internal CDK repo; introducing Storybook to aid component build out; artillery performance testing; lambda performance tuning; a reusable proxy solution and Kafka to lambda enablement.
          - Working with product owners and teams to define and prioritise stories in a technically complex domain
          - Mentoring an inexperienced team via code reviews, pair programming, architectural overviews and lightning talks
          - Organizing and contributing to Well Architected Reviews for AWS workloads

      - layout: left
        title: Liberty IT, Belfast
        sub_title: Senior Software Engineer
        caption: April 2014 – May 2019
        description: | # this will include new lines to allow paragraphs
          **Roles and responsibilities included**:

          - Tech leading a number of agile projects and working closely with teams, product owners and business partners to define workloads
          - Delivering secure, stable and performant applications, working from project design through to delivery and monitoring/maintenance
          - Working on some of the first AWS cloud native architectures in Liberty Mutual, primarily learning through self-directed study
          - Developing applications with a Performance, Stability and Security (PSS) focussed mentality
          - Creating a PSS application and leading a cross-team initiative to engage teams to improve PSS aspects of their applications
          - Taking projects though security review processes and implementing an antivirus scanner to protect our resources against unsafe files
          - Mentoring and transitioning of workloads to remote teams, including spending two weeks in the US providing support to new teams
          - Building experience in a number of techniques including pair programming, exploratory testing, threat modelling, A/B testing and BDD

      - layout: left
        title: Liberty IT, Belfast
        sub_title: Associate Software Engineer / Software Engineer
        caption: June 2011 – April 2014
        description: | # this will include new lines to allow paragraphs
            **Roles and responsibilities included**:

            - Proving myself as a trusted and capable team member who could work on a variety of tasks autonomously
            - Quickly understanding and undertaking work in unfamiliar domains and technologies
            - Working closely with business partners and remote team members to deliver on projects, primarily via a waterfall methodology
            - Validating code deliveries via unit, integration and exploratory testing
            - Working with technical leaders and other project teams to gather requirements and implement an analytics framework in a high pressure environment
            - Participating in guidance teams to ensure code quality and consistency across teams
            - Representing LIT at external events such as graduate science fairs

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: EOR Billing

        description: | # this will include new lines to allow paragraphs
          Highly scalable, event driven EOR bill generation and pricing

          **Technologies used**: AWS SAM, SQS, SNS, Typescript, Lambda, EventBridge, Step Functions, DynamodDB, Artillery Perforamnce Testing, New Relic.
      - layout: left
        title: Contractor Billing

        description: | # this will include new lines to allow paragraphs
          Complex scalable quoting for multiple contractors and invoices and integration with 3rd party payment vendor

          **Technologies used**: AWS SAM, SQS, SNS, EventBridge Pipes, Typescript, Lambda, EventBridge, Step Functions, DynamodDB, Artillery Perforamnce Testing, New Relic.
      - layout: left
        title: Pricing Service

        description: | # this will include new lines to allow paragraphs
         Once of the first Serverless projects within GP, moving a mission critical service to a team owned, serverless solution
          
          **Technologies used**: AWS SAM, SQS, SNS, Typescript, Lambda,  DynamodDB, Artillery Perforamnce Testing, New Relic.
      - layout: left
        title: Distribution Capabilities Platform

        description: | # this will include new lines to allow paragraphs
          Product agnostic and event driven services to enable faster development of future quoting systems.

          **Technologies used**: CFT, CDK, Serverless, Lambda, SNS, SQS, API Gateway, DynamoDB, DocumentDB, React, Typescript, NodeJS, GraphQL, REST, Git, Bamboo, Splunk, Datadog. Experimentation with EventBridge, AWS MSK and Kafka.

      - layout: left
        title: Oasis 2 Home Quoting

        description: | # this will include new lines to allow paragraphs
          UI and services to support quoting, rating and binding of home policies through liberymutual.com

          **Technologies used**: CFT, CDK, Serverless, Lambda, SNS, SQS, API Gateway, DynamoDB, React, Typescript, NodeJS, GraphQL, REST, Git, Bamboo, Splunk, Datadog.

      - layout: left
        title: Serverless Policy Endorsements (OPC)

        description: | # this will include new lines to allow paragraphs
          Event driven architecture to automate policy endorsement opportunities for customers.

          **Technologies used**: CFT, Lambda, Step Functions, Fargate, API Gateway, DynamoDB, S3, React, NodeJS, REST, Git, Jenkins.

      - layout: left
        title: Auto Damage Inspection at Liberty

        description: | # this will include new lines to allow paragraphs
          Cloud native mobile and agent applications to improve policy purchase time by enabling customers to upload vehicle images for approval

          **Technologies used**: Serverless, Lambda, API Gateway, DynamoDB, S3, React, Yaml, NodeJS, REST, Git, Jenkins. Experimentation with Rekognition and TextTract.

      - layout: left
        title: Previous Projects

        description: | # this will include new lines to allow paragraphs
          I have worked on a range of projects in the last 10 years, primarily within the Digital Service organization of Liberty Mutual, providing functionality for millions of users.

          **Technologies used**: React, DOJO, Java, IBM Process Server, BPEL, Siteminder, MongoDB, Drools.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Queen's University Belfast
        caption: 2006 - 2011
        sub_title: BSc Computing and Information Technology
        description: | # this will include new lines to allow paragraphs
          I received 1st class honours from my CIT course and received an award for best performing student on this course.

  - title: Interests
    layout: text
    content: | # this will include new lines to allow paragraphs
      Aside from technology, my other interests include barbecuing, running, reading and board gaming.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
